name: Test Pull Request

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      nexusd:
        image: ghcr.io/gammazero/nexusd:latest
        ports:
          - 8080:8080
        command: -realm test1 -ws 0.0.0.0:8080

    strategy:
      matrix:
        node-version: [24, 26]

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run check
      - run: npm test
